version: '3'
services:
  frontend:
    build: .
    image: mixnjuice-frontend:latest
    container_name: mixnjuice-frontend
    restart: always
    environment:
      VIRTUAL_HOST: ${WEB_HOST}
      VIRTUAL_PORT: ${WEB_PORT}
      LETSENCRYPT_HOST: ${WEB_HOST}
    networks:
      - proxy_proxy
networks:
  proxy_proxy:
    external: true
